apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - command:
        - /manager
        args:
        - --enable-leader-election
        - --proxy-url=storageos-proxy.storageos-etcd.svc
        image: controller
        env:
        - name: DISABLE_WEBHOOKS
          value: "true"
        name: manager
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 120Mi
      terminationGracePeriodSeconds: 10
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  namespace: system
  labels:
    control-plane: proxy
spec:
  selector:
    matchLabels:
      control-plane: proxy
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: proxy
    spec:
      containers:
      - name: proxy
        args:
          - --api-port=8080
        image: proxy
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 100m
            memory: 50Mi
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: proxy
  namespace: system
  labels:
    control-plane: proxy
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    control-plane: proxy
