name: Release Version
on:
  push:
    tags:      
      - "v[0-9]+.[0-9]+.[0-9]+"      

jobs:
  auto-release:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Make manifest
        run: make uber
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            storageos-etcd-cluster-operator.yaml     
            config/samples/storageos-etcd-cluster.yaml 
