name: Release Docker images
on:
  push:
    branches:
      - main      
    tags:      
      - "v[0-9]+.[0-9]+.[0-9]+"      

jobs:
  build-and-push:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
        with:
          # Need all the history for git describe --tags to work
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14.3'
      
      - name: Login to Quay 
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
      - name: Build and push Docker image to RH
        run: make docker-build-quay docker-push-quay

      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DH_USERNAME }}
          password: ${{ secrets.DH_PASSWORD }}
      - name: Build and push Docker image to DH
        run: make docker-build docker-push

